---

- hosts: all
  vars_files:
    - vars/main.yml
    - vars/vault.yml

  tasks:
    - name: Configure sudoers rules
      copy:
        src: usr/local/etc/sudoers.d/ansible
        dest: /usr/local/etc/sudoers.d/ansible
        owner: root
        group: wheel
        mode: 0444
        validate: /usr/local/sbin/visudo -csf %s
      become: yes

    - name: Configure SSH
      copy:
        src: etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config
        owner: root
        group: wheel
        mode: 0644
        validate: /usr/sbin/sshd -tf %s
      become: yes
      notify: Restart SSH

    - name: Configure motd
      copy:
        src: etc/motd
        dest: /etc/motd
        owner: root
        group: wheel
        mode: 0644
      become: yes

    - name: Create /srv directory
      file:
        path: /srv
        owner: root
        group: wheel
        mode: 0755
        state: directory
      become: yes

    - name: Install Restic
      package:
        name: restic
        state: present
      become: yes

    - name: Create /root/bin
      file:
        path: /root/bin
        owner: root
        group: wheel
        mode: 0770
        state: directory
      become: yes

    - name: Copy nightly backup script
      template:
        src: root/bin/backup-to-backblaze.j2
        dest: /root/bin/backup-to-backblaze
        owner: root
        group: wheel
        mode: 0550
      become: yes

    - name: Configure nightly backup cron job
      cron:
        name: restic backup
        minute: "0"
        hour: "0"
        job: /root/bin/backup-to-backblaze
        state: present
      become: yes

    - name: Configure rc.d
      template:
        src: etc/rc.conf
        dest: /etc/rc.conf
        owner: root
        group: wheel
        mode: 0644
        # TODO: Add rc.conf validation
        #validate:
      become: yes
      notify: Reload services

    - name: Install nginx
      package:
        name: nginx
        state: present
      become: yes

    - name: Start nginx
      service:
        name: nginx
        state: started
      become: yes

    - name: Create /usr/local/www/www.sdcc.sh
      file:
        path: /usr/local/www/www.sdcc.sh
        owner: root
        group: wheel
        mode: 0755
        state: directory
      become: yes

    - name: Create index.html
      copy:
        content: Hello, world! <a href="https://www.sdcc.sh/services.txt">Available services</a>.
        dest: /usr/local/www/www.sdcc.sh/index.html
        owner: root
        group: wheel
        mode: 0644
      become: yes

    - name: Create services.txt
      copy:
        content: |
          # SERVICE     PORT/PROTOCOL URL                         DESCRIPTION
          ssh           22/tcp        # ssh://sdcc.sh             SSH Remote Login Protocol
          www           443/tcp       # https://www.sdcc.sh       This website
          subsonic      443/tcp       # https://subsonic.sdcc.sh  Subsonic-compatible Music streaming server
          bittorrent    6881/udp      #                           rTorrent BitTorrent client DHT
          bittorrent    50000/udp     #                           rTorrent BitTorrent client
          bittorrent    50000/tdp     #                           rTorrent BitTorrent client
        dest: /usr/local/www/www.sdcc.sh/services.txt
        owner: root
        group: wheel
        mode: 0644
      become: yes

    - name: Configure nginx
      copy:
        src: usr/local/etc/nginx/nginx.conf
        dest: /usr/local/etc/nginx/nginx.conf
        owner: root
        group: wheel
        mode: 0644
        validate: /usr/local/sbin/nginx -t -c %s
      become: yes
      notify: Reload nginx

    - name: Install navidrome
      package:
        name: navidrome
        state: present
      become: yes

    - name: Start navidrome
      service:
        name: navidrome
        state: started
      become: yes

    - name: Create music-rw user group
      group:
        name: music-rw
        state: present
      become: yes

    - name: Create /srv/subsonic directory
      file:
        path: /srv/subsonic
        owner: root
        group: wheel
        mode: 0755
        state: directory
      become: yes

    - name: Create music directory
      file:
        path: /srv/subsonic/music
        owner: root
        group: music-rw
        mode: 0775
        state: directory
      become: yes

    - name: Configure navidrome
      copy:
        src: usr/local/etc/navidrome/config.toml
        dest: /usr/local/etc/navidrome/config.toml
        owner: root
        group: wheel
        mode: 0644
      become: yes
      notify: Restart navidrome

    - name: Install rtorrent
      package:
        name: rtorrent
        state: present
      become: yes

    - name: Install rtorrent rc.d script
      copy:
        src: usr/local/etc/rc.d/rtorrent
        dest: /usr/local/etc/rc.d/rtorrent
        owner: root
        group: wheel
        mode: 0755
      become: yes

    - name: Create torrents-rw user group
      group:
        name: torrents-rw
        state: present
      become: yes

    - name: Create rtorrent user
      user:
        name: rtorrent
        groups: [torrents-rw]
        password: "*"
        shell: /usr/sbin/nologin
        append: yes
        create_home: no
        state: present
      become: yes

    - name: Create /var/log/rtorrent directory
      file:
        path: /var/log/rtorrent
        owner: root
        group: rtorrent
        mode: 0775
        state: directory
      become: yes

    - name: Create /var/run/rtorrent directory
      file:
        path: /var/run/rtorrent
        owner: root
        group: rtorrent
        mode: 0775
        state: directory
      become: yes

    - name: Start rtorrent
      service:
        name: rtorrent
        state: started
      become: yes

    - name: Create /srv/bittorrent directory
      file:
        path: /srv/bittorrent
        owner: root
        group: wheel
        mode: 0755
        state: directory
      become: yes

    - name: Create /srv/bittorrent/torrents/load directory
      file:
        path: /srv/bittorrent/torrents/load
        owner: root
        group: torrents-rw
        mode: 0775
        state: directory
      become: yes

    - name: Create /srv/bittorrent/torrents/start directory
      file:
        path: /srv/bittorrent/torrents/start
        owner: root
        group: torrents-rw
        mode: 0775
        state: directory
      become: yes

    - name: Create /srv/bittorrent/downloads directory
      file:
        path: /srv/bittorrent/downloads
        owner: root
        group: torrents-rw
        mode: 0775
        state: directory
      become: yes

    - name: Create /usr/local/etc/rtorrent directory
      file:
        path: /usr/local/etc/rtorrent
        owner: root
        group: wheel
        mode: 0755
        state: directory
      become: yes

    - name: Configure rtorrent
      copy:
        src: usr/local/etc/rtorrent/rtorrent.rc
        dest: /usr/local/etc/rtorrent/rtorrent.rc
        owner: root
        group: wheel
        mode: 0644
      become: yes
      notify: Restart rtorrent

    - name: Configure pf
      copy:
        src: etc/pf.conf
        dest: /etc/pf.conf
        owner: root
        group: wheel
        mode: 0644
        validate: pfctl -vnf %s
      become: yes
      notify: Reload pf

    - name: Install rsync
      package:
        name: rsync
        state: present
      become: yes


  handlers:
    - name: Reload services
      command: service -R
      become: yes

    - name: Restart SSH
      service:
        name: sshd
        state: restarted
      become: yes

    - name: Reload nginx
      service:
        name: nginx
        state: reloaded
      become: yes

    - name: Restart navidrome
      service:
        name: navidrome
        state: restarted
      become: yes

    - name: Restart rtorrent
      service:
        name: rtorrent
        # No reload option
        state: restarted
      become: yes

    - name: Reload pf
      command: |
        kldload pf
        pfctl -F all -f /etc/pf.conf
        # TODO: Do we want to defer this? Most likely it will
        # kill the SSH connection before Ansible disconnects.
        pfctl -e
      become: yes
