#!/bin/sh

. /etc/rc.subr

name="rtorrent"
rcvar="rtorrent_enable"

load_rc_config $name

: ${rtorrent_user:="rtorrent"}
: ${rtorrent_group:="rtorrent"}
: ${rtorrent_config:="/usr/local/etc/rtorrent/rtorrent.rc"}

procname="/usr/local/bin/rtorrent"
pidfile="/var/run/${name}/${name}.pid"
command="/usr/sbin/daemon"
command_args="-p ${pidfile} -f ${procname} -n -o system.daemon.set=true,import=${rtorrent_config}"

run_rc_command "$1"
